name: ${APP_IDENTIFIER:-railsfoundry}

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    environment:
      APP_IDENTIFIER: ${APP_IDENTIFIER:-railsfoundry}
      APP_NAME: ${APP_NAME:-RailsFoundry}
    depends_on:
      selenium:
        condition: service_started

  selenium:
    image: selenium/standalone-chromium
    restart: unless-stopped
